-- 001_initial_schema.sql
-- Online Garage: initial Supabase schema and Row Level Security policies.
-- Tables: vehicles, maintenance_records, vehicle_data_logs, symptom_rules.
-- This migration is not executed automatically; review before running.

-- ============================================================================
-- 1. public.vehicles
-- One row per vehicle owned by an authenticated user.
-- ============================================================================
create table public.vehicles (
    id                  uuid primary key default gen_random_uuid(),
    user_id             uuid not null references auth.users(id) on delete cascade,
    year                integer not null,
    make                text not null,
    model               text not null,
    mileage             numeric not null default 0,
    vin                 text,
    status              text not null default 'Active Garage Vehicle',
    battery_voltage     numeric,
    fuel_level          numeric,
    engine_temperature  numeric,
    dtc_code            text,
    last_synced_at      timestamptz,
    created_at          timestamptz not null default now(),

    -- Reasonable model year bounds; upper bound leaves room for near-future model years.
    constraint vehicles_year_range check (year between 1886 and 2100),
    constraint vehicles_mileage_non_negative check (mileage >= 0),
    -- VINs are always 17 characters when present; allow null for vehicles not yet identified.
    constraint vehicles_vin_length check (vin is null or char_length(vin) = 17),
    constraint vehicles_fuel_level_range check (fuel_level is null or (fuel_level between 0 and 100))
);

comment on table public.vehicles is 'Vehicles tracked in a user''s garage, including latest known telemetry snapshot.';

-- Speeds up "list my vehicles" queries and RLS ownership checks.
create index idx_vehicles_user_id on public.vehicles(user_id);

-- ============================================================================
-- 2. public.maintenance_records
-- Service history entries tied to a specific vehicle and its owner.
-- ============================================================================
create table public.maintenance_records (
    id              uuid primary key default gen_random_uuid(),
    user_id         uuid not null references auth.users(id) on delete cascade,
    vehicle_id      uuid not null references public.vehicles(id) on delete cascade,
    service_date    date not null,
    mileage         numeric not null,
    description     text not null,
    replaced_parts  text,
    notes           text,
    created_at      timestamptz not null default now(),

    constraint maintenance_records_mileage_non_negative check (mileage >= 0)
);

comment on table public.maintenance_records is 'Service/maintenance history entries for a vehicle.';

create index idx_maintenance_records_user_id on public.maintenance_records(user_id);
create index idx_maintenance_records_vehicle_id on public.maintenance_records(vehicle_id);

-- ============================================================================
-- 3. public.vehicle_data_logs
-- Append-only telemetry snapshots collected for a vehicle over time.
-- ============================================================================
create table public.vehicle_data_logs (
    id                  uuid primary key default gen_random_uuid(),
    user_id             uuid not null references auth.users(id) on delete cascade,
    vehicle_id          uuid not null references public.vehicles(id) on delete cascade,
    mileage             numeric not null,
    battery_voltage     numeric,
    fuel_level          numeric,
    engine_temperature  numeric,
    dtc_code            text,
    created_at          timestamptz not null default now()
);

comment on table public.vehicle_data_logs is 'Append-only telemetry history; browser clients may only insert and read, never modify or delete.';

create index idx_vehicle_data_logs_user_id on public.vehicle_data_logs(user_id);
create index idx_vehicle_data_logs_vehicle_id on public.vehicle_data_logs(vehicle_id);

-- ============================================================================
-- 4. public.symptom_rules
-- Shared reference/lookup data for diagnostic suggestions. Not user-owned.
-- ============================================================================
create table public.symptom_rules (
    id                       bigint generated by default as identity primary key,
    symptom                  text not null,
    possible_issue           text not null,
    urgency                  text not null,
    recommended_next_step    text not null,
    created_at               timestamptz not null default now()
);

comment on table public.symptom_rules is 'Static diagnostic reference data, readable by all clients, writable only via privileged (service_role) access.';

-- ============================================================================
-- Row Level Security
-- ============================================================================
alter table public.vehicles enable row level security;
alter table public.maintenance_records enable row level security;
alter table public.vehicle_data_logs enable row level security;
alter table public.symptom_rules enable row level security;

-- ----------------------------------------------------------------------------
-- vehicles: owners have full CRUD over their own rows only.
-- ----------------------------------------------------------------------------
create policy "Users can select their own vehicles"
    on public.vehicles
    for select
    to authenticated
    using (auth.uid() = user_id);

create policy "Users can insert their own vehicles"
    on public.vehicles
    for insert
    to authenticated
    with check (auth.uid() = user_id);

create policy "Users can update their own vehicles"
    on public.vehicles
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "Users can delete their own vehicles"
    on public.vehicles
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- maintenance_records: owners have full CRUD over their own rows only.
-- Insert/update additionally require that the referenced vehicle belongs
-- to the same authenticated user, preventing records being attached to
-- someone else's vehicle.
-- ----------------------------------------------------------------------------
create policy "Users can select their own maintenance records"
    on public.maintenance_records
    for select
    to authenticated
    using (auth.uid() = user_id);

create policy "Users can insert maintenance records for their own vehicles"
    on public.maintenance_records
    for insert
    to authenticated
    with check (
        auth.uid() = user_id
        and exists (
            select 1
            from public.vehicles v
            where v.id = maintenance_records.vehicle_id
              and v.user_id = auth.uid()
        )
    );

create policy "Users can update maintenance records for their own vehicles"
    on public.maintenance_records
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (
        auth.uid() = user_id
        and exists (
            select 1
            from public.vehicles v
            where v.id = maintenance_records.vehicle_id
              and v.user_id = auth.uid()
        )
    );

create policy "Users can delete their own maintenance records"
    on public.maintenance_records
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- vehicle_data_logs: owners may read and append their own rows only.
-- No update/delete policies are defined, so RLS denies those actions for
-- every browser-facing role regardless of grants (defense in depth below).
-- ----------------------------------------------------------------------------
create policy "Users can select their own vehicle data logs"
    on public.vehicle_data_logs
    for select
    to authenticated
    using (auth.uid() = user_id);

create policy "Users can insert vehicle data logs for their own vehicles"
    on public.vehicle_data_logs
    for insert
    to authenticated
    with check (
        auth.uid() = user_id
        and exists (
            select 1
            from public.vehicles v
            where v.id = vehicle_data_logs.vehicle_id
              and v.user_id = auth.uid()
        )
    );

-- ----------------------------------------------------------------------------
-- symptom_rules: public reference data, readable by anyone; no browser-side
-- write policies are defined, so writes are only possible via service_role
-- (which bypasses RLS entirely).
-- ----------------------------------------------------------------------------
create policy "Anyone can select symptom rules"
    on public.symptom_rules
    for select
    to anon, authenticated
    using (true);

-- ============================================================================
-- Grants
-- RLS policies are the primary access control; grants are scoped to match
-- them so that permissions are correct even before/without RLS in effect.
-- ============================================================================
grant select, insert, update, delete on public.vehicles to authenticated;
grant select, insert, update, delete on public.maintenance_records to authenticated;

-- Browser clients may only read and append telemetry, never modify/delete it.
grant select, insert on public.vehicle_data_logs to authenticated;

-- Reference data: readable by anyone, including signed-out visitors; no
-- insert/update/delete granted to anon or authenticated.
grant select on public.symptom_rules to anon, authenticated;
